### ISSUE TITLE
zcl does not pick issue id from commit title

### ISSUE THREAD

**Issue by sdorokhova** [zeebe-io/zeebe-changelog#7]
**Problem description**

In Tasklist we currently place issue id at the very beginning of commit title, e.g.
```
#1010 Fix persistent sessions (#1033)
```
ZCL tool only picks the id from the lines containing `closes` or `related` etc.: https://github.com/zeebe-io/zeebe-changelog/blob/c84d9879e4f99b8452bdaa738325f3b8df31be1f/pkg/gitlog/gitlog.go#L12

Would be nice to also pick it from beginning of commit title.

**Comment by npepinpe** [comment]
Closing as Operate/Tasklist does not use it anymore.
